name: Build desktop app & publish it to github release
on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build (${{ matrix.os }} - ${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Build for supported platforms
        # https://github.com/electron/electron-packager/blob/ebcbd439ff3e0f6f92fa880ff28a8670a9bcf2ab/src/targets.js#L9
        # 32-bit Linux unsupported as of 2019: https://www.electronjs.org/blog/linux-32bit-support
        os: [ubuntu-latest, windows-latest]
        arch: [x64]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install
        run: npm i
      - name: Make
        run: npm run build:desktop -- --arch=${{ matrix.arch }}
      - name: Release
        run: npm run publish:desktop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
