name: Deploy site and app

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # PikaTorrent site
      - name: Build site
        run: npm ci && npm run build:site
      - name: Publish site
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: pikatorrent-site
          directory: apps/site/out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      # PikaTorrent app
      - name: Build app
        run: npm ci && SIGNALING_URL=${{ vars.SIGNALING_URL }} npm run build:web
      - name: Publish app
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: pikatorrent-app
          directory: apps/app/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
